# FiveThirtyEight

This is my first simulation notebook, inspired by [David Robinson's youtube screencast](https://www.youtube.com/watch?v=XEsNpxl5b1M).

Hopefully this will become a regular exercise for me.

**Source:**

-   https://fivethirtyeight.com/features/can-you-get-the-gloves-out-of-the-box/

## Riddler Express

> These days I always have a pack of latex gloves nearby. But it's notoriously difficult to pull exactly two gloves out of the box at a time. Sometimes I'll pull out two gloves, other times three, and yet other times four. **Somehow, I never pull out any other number of gloves at a time.**
>
> This morning, I noticed that there are 10 gloves left in the box. How many distinct ways are there for me to remove all 10 gloves from the box? Note that the order matters here --- for example, pulling out two gloves, then four gloves and then another four gloves is distinct from pulling out four gloves, another four gloves and then two gloves.

This is a counting exercise.

Basically, we are finding sequences of 2, 3, and 4s that add up to 10.

**Pen and paper**:

-   $\{2, 2, 2, 2, 2\} \times 1$

-   $\{4, 2, 2, 2\} \times 4$

-   $\{4, 4, 2\} \times 3$

-   $\{3, 3, 4\} \times 3$

-   $\{3, 3, 2, 2\} \times 5$

*Total*: $1 + 3 + 3 + 4 + 5 = 16$

## Riddler Classic

> From Chris Nho comes a question of rolling (and re-rolling) a die:
>
> You start with a fair 6-sided die and roll it six times, recording the results of each roll. You then write these numbers on the six faces of another, unlabeled fair die. For example, if your six rolls were 3, 5, 3, 6, 1 and 2, then your second die wouldn't have a 4 on it; instead, it would have two 3s.
>
> Next, you roll this second die six times. You take those six numbers and write them on the faces of yet another fair die, and you continue this process of generating a new die from the previous one.
>
> Eventually, you'll have a die with the same number on all six faces. What is the average number of rolls it will take to reach this state?
>
> Extra credit: Instead of a standard 6-sided die, suppose you have an N-sided die, whose sides are numbered from 1 to N. What is the average number of rolls it would take until all N sides show the same number?

```{r}
# https://fivethirtyeight.com/features/can-you-get-the-gloves-out-of-the-box/

die <- 1:6

die <- sample(die, replace = TRUE)
die <- sample(die, replace = TRUE)
die <- sample(die, replace = TRUE)
## etc.
die

die <- 1:6
n <- 0
while (length(unique(die)) > 1) {
  die <- sample(die, replace = TRUE)
  n <- n + 1
}
die
n

simulation <- function(num_sides = 6) {
  die <- 1:num_sides
  n <- 0
  while (length(unique(die)) > 1) {
    die <- sample(die, replace = TRUE)
    n <- n + 1
  }
  return(n)
}

result <- replicate(1e4, simulation())
mean(result)
hist(result)

library(tidyverse)
result <- map_dbl(1:1e4, ~ simulation())
mean(result)

accumulate(1:10, ~ sample(., replace = TRUE), .init = 1:6)


simulate_with_purrr <- function(num_sides = 6) {
  rolls <- accumulate(1:1e3, function(x, ...) {
    die <- sample(x, replace = TRUE) 
  
      if (length(unique(die)) == 1) {
        done(die)
      } else {
        die
      }
    }, .init = 1:num_sides)
  return(length(rolls) - 1)
}

result <- replicate(100, simulate_with_purrr(50))

result


df <- crossing(num_sides = 1:10, trial = 1:1000) %>% 
  mutate(sim = map_dbl(num_sides, simulate_with_purrr))
df

df %>% 
  group_by(num_sides) %>% 
  summarize(avg = mean(sim)) %>% 
  ggplot(aes(num_sides, avg)) + 
  geom_point() + 
  geom_smooth(method = lm)

df_avg <- df %>% 
  group_by(num_sides) %>% 
  summarize(avg = mean(sim))

lm(avg ~ num_sides, data = df_avg %>% filter(num_sides > 1))

df %>% 
  ggplot(aes(x = sim)) + 
  geom_histogram(binwidth = 1) + 
  facet_wrap(~ num_sides, scales = "free_y")
```
